name: evaluate

on:
  push:
    paths:
      - "peft_bench.yaml"

  pull_request:
    paths:
      - "peft_bench.yaml"

jobs:
  run-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install peft transformers "lm_eval==0.3.0" huggingface_hub pyyaml pandas pyarrow

      - name: Run evaluation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_REPO: ${{ secrets.HF_DATASET_REPO }}
        run: |
          export HF_TOKEN=$HF_TOKEN
          python run_eval.py       
